### ISSUE TITLE
Remove prettier config

### ISSUE THREAD

**Issue by jakub300** [xfiveco/eslint-config-chisel#1]
It overrides config from `.prettierrc`, we don't want that.

We should probably put `.prettierrc` only in Chisel but I'm open for alternatives.

**Comment by arturkot** [comment]
What do you mean by "prettier config"? Do you mean settings inside `index.js`: `"prettier/prettier"`?

**Comment by arturkot** [comment]
Fixed in 47e58c7fe3ea7641ca7d289dff92ea92c4dd6d30
