### ISSUE TITLE
Setup greenkeeper

### ISSUE THREAD

**Issue by jakub300** [xfiveco/eslint-config-chisel#2]
I think it would cool to try [Greenkeeper](https://greenkeeper.io/) on this project after we release it. What do you think @luboskmetko?

**Comment by luboskmetko** [comment]
@jakub300 sure, we could try. I've installed it for this repository. Currently it says that _Greenkeeper’s Initial Pull Request hasn’t arrived yet. Depending on your tests and a number of other factors, the Initial Pull Request may take up to 30 minutes to show up._
